config/routes.rb
Rails.application.routes.draw do
  get 'serials/index'
  get 'serials/new'
  get 'serials/create'
  post "serials",         to:"serials#create"

  get 'documentfilms/index'
  get 'documentfilms/new'
  post "documentfilms",         to:"documentfilms#create"
  get 'movies/index'
  get 'movies/new'
  post 'movies',                to:"movies#create"


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "serials#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/documentfilm.rb
class Documentfilm < ApplicationRecord
end

app/models/movie.rb
class Movie < ApplicationRecord
end

app/models/serial.rb
class Serial < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documentfilms_controller.rb
class DocumentfilmsController < ApplicationController
  def index

    @documents = Documentfilm.all

  end

  def new
      @document = Documentfilm.new
  end

  def create
      @document = Documentfilm.new(post_params)

      if @document.save
        redirect_to documentfilms_index_path
        #root_path
      else 
        render :new
      end 
  end

  private
  
  def post_params
    params.require(:documentfilm).permit(:name, :synopsis,:director)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index

    @movies = Movie.all

  end

  def new
      @movie = Movie.new
  end

  def create
      @movie = Movie.new(post_params)

      if @movie.save
        redirect_to movies_index_path
        #root_path
      else 
        render :new
      end 
  end

  private
  
  def post_params
    params.require(:movie).permit(:name, :synopsis,:director)
  end
end

app/controllers/serials_controller.rb
class SerialsController < ApplicationController
  def index

    @serials = Serial.all

  end

  def new
      @serial = Serial.new
  end

  def create
      @serial = Serial.new(post_params)

      if @serial.save
        redirect_to serials_index_path
        #root_path
      else 
        render :new
      end 
  end

  private
  
  def post_params
    params.require(:serial).permit(:name, :synopsis,:director)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documentary_films_helper.rb
module DocumentaryFilmsHelper
end

app/helpers/documentfilms_helper.rb
module DocumentfilmsHelper
end

app/helpers/movie_helper.rb
module MovieHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/serials_helper.rb
module SerialsHelper
end

app/views/documentfilms/index.html.erb
<h1>Mostrando todas Document Films</h1>
<p><% @documents.each do |document| %>
    <h2><%= document.name %></h2>
    <p> <%= document.synopsis %></p>
    <p> <%= document.director %></p>

    <% end %>
</p>

<%= link_to "Agregar nuevo Document", documentfilms_new_path, class:"btn btn-primary" %>

app/views/documentfilms/new.html.erb
<div class="container">

<h1 class="text-center">Crear Document</h1>
<br><br>

<%= form_with model: @document do |form|  %>
    <div class="border p-5 shadow col-4">
            <div class="mb-3">
                <%=  form.label :name, "Título del Document Films",class:"form-label" %>
                <%=  form.text_field :name ,class:"form-control"%>

            </div>
            <div class="mb-5">
                <%= form.label :synopsis, "Synopsis",class:"form-label" %>
                <%= form.text_field :synopsis,class:"form-control" %>
            </div>
            <div class="mb-5">
                <%= form.label :director, "Director",class:"form-label" %>
                <%= form.text_field :director,class:"form-control" %>
            </div>

            <div class="text-center">
                <%= form.submit "Enviar",class:"btn btn-primary mb-3"%>
            </div>
    </div>

<% end %>
</div>
<div class="text-center">
    <%= link_to "Ir al inicio de las Series", documentfilms_index_path, class:"btn btn-primary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Peliculas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">Peliculas</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                  <li class="nav-item">
                     <%= link_to "Home", root_path,class:"nav-link active" %>
                  </li>
                  <li class="nav-item">
                     <%= link_to "Movies", movies_index_path,class:"nav-link active" %>
                  </li>
                  <li class="nav-item">
                      <%= link_to "Documentary Film", documentfilms_index_path,class:"nav-link active" %>

                  </li>
                  <li class="nav-item">
                     <%= link_to "Serials", serials_index_path,class:"nav-link active" %>
                  </li>
                </ul>
              </div>
            </div>
</nav>
  <div class="container">
    <%= yield %>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
  </body>
</html>

app/views/movies/index.html.erb
<h1>Mostrando todas Movies</h1>
<p><% @movies.each do |movie| %>
    <h2><%= movie.name %></h2>
    <p> <%= movie.synopsis %></p>
    <p> <%= movie.director %></p>

    <% end %>
</p>

<%= link_to "Agregar nuevo Post", movies_new_path, class:"btn btn-primary" %>

app/views/movies/new.html.erb
<div class="container">

<h1 class="text-center">crear Movie</h1>
<br><br>

<%= form_with model: @movie, method: :post do |form|  %>
    <div class="border p-5 shadow col-4">
            <div class="mb-3">
                <%=  form.label :name, "Título del Movie",class:"form-label" %>
                <%=  form.text_field :name ,class:"form-control"%>

            </div>
            <div class="mb-5">
                <%= form.label :synopsis, "Synopsis",class:"form-label" %>
                <%= form.text_field :synopsis,class:"form-control" %>
            </div>
            <div class="mb-5">
                <%= form.label :director, "Director",class:"form-label" %>
                <%= form.text_field :director,class:"form-control" %>
            </div>

            <div class="text-center">
                <%= form.submit "Enviar",class:"btn btn-primary mb-3"%>
            </div>
    </div>

<% end %>
</div>
<div class="text-center">
    <%= link_to "Ir al inicio de las Movie", movies_index_path, class:"btn btn-primary" %>
</div>

app/views/serials/index.html.erb
<h1>Mostrando todas Serials</h1>
<p><% @serials.each do |serial| %>
    <h2><%= serial.name %></h2>
    <p> <%= serial.synopsis %></p>
    <p> <%= serial.director %></p>

    <% end %>
</p>

<%= link_to "Agregar nueva Serie", serials_new_path, class:"btn btn-primary" %>

app/views/serials/new.html.erb
<div class="container">

<h1 class="text-center">Crear Seires</h1>
<br><br>

<%= form_with model: @serial do |form|  %>
    <div class="border p-5 shadow col-4">
            <div class="mb-3">
                <%=  form.label :name, "Título de la Serie",class:"form-label" %>
                <%=  form.text_field :name ,class:"form-control"%>

            </div>
            <div class="mb-5">
                <%= form.label :synopsis, "Synopsis",class:"form-label" %>
                <%= form.text_field :synopsis,class:"form-control" %>
            </div>
            <div class="mb-5">
                <%= form.label :director, "Director",class:"form-label" %>
                <%= form.text_field :director,class:"form-control" %>
            </div>

            <div class="text-center">
                <%= form.submit "Enviar",class:"btn btn-primary mb-3"%>
            </div>
    </div>

<% end %>
</div>
<div class="text-center">
    <%= link_to "Ir al inicio de las Series", serials_index_path, class:"btn btn-primary" %>
</div>